# Generated by Django 3.1 on 2020-08-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='role',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='role',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
