# Generated by Django 3.1 on 2020-08-18 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=128)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_id', models.IntegerField(default=meters.models.make_card_id, editable=False, primary_key=True, serialize=False, verbose_name='Meter ID')),
                ('meter_token', models.IntegerField(default=meters.models.make_token, editable=False)),
                ('customer_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Customer Balance')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('billing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meters.billing')),
                ('stake_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to='users.stakeholder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
