# Generated by Django 3.1 on 2020-08-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
