# Generated by Django 3.1 on 2020-08-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='customer_balance',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True, verbose_name='Customer Balance'),
        ),
    ]
