# Generated by Django 3.1 on 2020-08-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_auto_20200818_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='customer_balance',
            field=models.IntegerField(verbose_name='Customer Balance'),
        ),
    ]
